### ISSUE TITLE
working with arrays quiz

### ISSUE THREAD

**Issue by ethanfree23** [learn-co-curriculum/phase-1-quiz-working-with-arrays-in-javascript-quiz#2]
### Canvas Link

https://learning.flatironschool.com/courses/4557/quizzes/24649

### Concern

the source for forEach() is linked to finding array elements (https://learning.flatironschool.com/courses/4557/pages/finding-array-elements?module_item_id=335590), not (https://learning.flatironschool.com/courses/4557/pages/foreach-the-unexpressive-iterator?module_item_id=335597)

**Comment by ihollander** [comment]
Hi @ethanfree23 - thanks for flagging! We'll update the links to point to the correct lessons.
