### ISSUE TITLE
Grammar Error

### ISSUE THREAD

**Issue by jlswift2** [learn-co-curriculum/phase-1-quiz-working-with-arrays-in-javascript-quiz#4]
### Canvas Link

https://learning.flatironschool.com/courses/4992/quizzes/26461

### Concern

There is a grammar error in question 9 of the Working with Arrays in JavaScript Quiz.

### Additional Context

"The .map() method take a callback function as an argument."

### Suggested Changes

Add an "s" after "method" or after "take".

**Comment by lizbur10** [comment]
Hi @jlswift2 ! Thanks for bringing this to our attention - the error has been fixed. 💙
