### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by EinzigeMeister** [learn-co-curriculum/phase-1-quiz-working-with-arrays-in-javascript-quiz#5]
The link to forEach: The Unexpressive Iterator (https://my.learn.co/courses/650/pages/foreach-the-unexpressive-iterator?module_item_id=143586) leads to the course homepage with the following errors:
The page "Foreach The Unexpressive Iterator" does not exist.
That page has been disabled for this course

**Comment by EinzigeMeister** [comment]
recommend it directed to 
forEach: The Iterator of No Return
(https://my.learn.co/courses/650/pages/foreach-the-iterator-of-no-return?module_item_id=83200)

**Comment by lizbur10** [comment]
Hi @EricsFlatironAcct! Thanks for bringing this to our attention. The broken link in questions 2 and 6 has now been fixed. 💙
