### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by ahmadalashtar** [learn-co-curriculum/phase-1-quiz-working-with-arrays-in-javascript-quiz#6]
Question 9
Expected: The .map() method takes a callback function as an argument. 
Actual: The .map() method take a callback function as an argument.

**Comment by lizbur10** [comment]
Hi @ahmadalashtar01! Thanks for bringing this to our attention. This error has been fixed. Note that you may not see it in your Canvas instance, but it will be present for students moving forward. 💙
