### ISSUE TITLE
Working with Arrays in JavaScript Quiz 

### ISSUE THREAD

**Issue by goodbuddyo** [learn-co-curriculum/phase-1-quiz-working-with-arrays-in-javascript-quiz#7]
### Canvas Link

https://my.learn.co/courses/650/quizzes/6982?module_item_id=83202

### Concern

For Question 6, 
Select all that apply. The best use cases for the forEach() method are:

In my first quiz attempt, I checked the following boxes but was marked incorrect

-  To iterate through an array to log values. 
Correct!
forEach() is great for logging all the values in an array!

-   To create a new array with updates to our original elements. 
While we could create a new empty array and then use forEach() to push updated elements from a different array into it, there are a few other iterators that can do this job a little better for us. Check out .map(), for instance!

In my second quiz attempt, I checked only 
-  To iterate through an array to log values. 
 
 but was given only partial credit. 
 Since the other two answers were incorrect, I am puzzled as to why this has been graded as partial.

- To iterate over an array and directly mutate elements. 
and
 I don't know 
and 

### Additional Context

Question 6
0.5 / 1 pts
Select all that apply. The best use cases for the forEach() method are:
  To iterate over an array and directly mutate elements. 

  To iterate through an array to log values. 
Correct!
forEach() is great for logging all the values in an array!

  I don't know.

  To create a new array with updates to our original elements. 

Source/s:
	•	[forEach: The Unexpressive Iterator](https://my.learn.co/courses/650/pages/foreach-the-unexpressive-iterator?module_item_id=143586)

### Suggested Changes

Please let me know if I am missing something.

**Comment by lizbur10** [comment]
Hi again @goodbuddyo! The other intended correct answer to this question is "To iterate over an array and directly mutate elements." As the only iterator that doesn't automatically create and return a **new** array, this is a use for which `forEach` is appropriate. 

I can see why the question is misleading, however: generally speaking, directly mutating an array is not recommended, so calling it a "best" use case is questionable. I have adjusted the wording in a way that I think better reflects the intention of the question.

Thanks again for contributing to the curriculum 💙
